name: Post to X

on:
  schedule:
    - cron: '0 10 * * *'  # 毎日19時（日本時間）に投稿
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Post a tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: "こんにちは、GitHub Actionsから自動投稿です！"
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
